repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: mixed-line-ending
        args: [--fix=lf]
  - repo: local
    hooks:
      - id: meson-setup
        name: meson setup (if needed)
        entry: bash -c 'if [ ! -d builddir ]; then CC=clang CXX=clang++ meson setup builddir --native-file clang-native.ini; fi'
        language: system
        pass_filenames: false
        always_run: true
      - id: clang-format
        name: clang-format
        entry: ninja -C builddir clang-format-check
        language: system
        types: [c++]
        pass_filenames: false
      - id: clang-tidy
        name: clang-tidy
        entry: ninja -C builddir clang-tidy
        language: system
        types: [c++]
        pass_filenames: false
