name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  ci:
    name: CI
    runs-on: self-hosted
    container: woodflow-ci-runner:local
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Run pre-commit
        run: pre-commit run --all-files
      - name: Setup Meson
        run: CC=clang CXX=clang++ meson setup builddir --native-file clang-native.ini
      - name: Build
        run: meson compile -C builddir
      - name: Run tests
        run: meson test -C builddir --print-errorlogs
