name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  pre-commit:
    name: setup bazel and pre-commit
    runs-on: self-hosted
    container: &container-config
      image: ubuntu:latest
      volumes:
        - bazel-disk-cache:/tmp/bazel-disk-cache
        - bazel-repo-cache:/tmp/bazel-repo-cache
    steps:
      - &install-git
        name: Install git
        run: |
          apt-get update -qq
          apt-get install -y git libxml2-dev
      - name: Install python
        run: |
          apt-get update -qq
          apt-get install -y python3 python3-pip libxml2
      - &setup-bazel
        name: Setup Bazel
        uses: bazel-contrib/setup-bazel@0.15.0
        with:
          bazelisk-version: "1.x"
      - &checkout
        name: Checkout code
        uses: actions/checkout@v5
        with:
          submodules: recursive
      - &fix-git
        name: Fix git ownership
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: Verify Bazel installation
        run: bazel version
      - name: Fetch Bazel dependencies
        run: bazel fetch --config=ci //...
      - name: Install pre-commit
        run: pip3 install --break-system-packages pre-commit
      - name: Run pre-commit
        run: pre-commit run --all-files
  build:
    name: build
    needs: pre-commit
    runs-on: self-hosted
    container: *container-config
    steps:
      - *install-git
      - *setup-bazel
      - *checkout
      - *fix-git
      - name: Build all targets
        run: bazel build --config=ci //...
  test:
    name: test
    needs: build
    runs-on: self-hosted
    container: *container-config
    steps:
      - *install-git
      - *setup-bazel
      - *checkout
      - *fix-git
      - name: Run tests
        run: bazel test --config=ci //...
  # test-lint:
  #   name: lint
  #   needs: test
  #   runs-on: self-hosted
  #   container: *container-config
  #   steps:
  #     - *install-git
  #     - *setup-bazel
  #     - *checkout
  #     - *fix-git
  #     - name: Lint
  #       run: bazel build --config=ci --config=lint //...
  # test-asan:
  #   name: test:asan
  #   needs: test
  #   runs-on: self-hosted
  #   container: *container-config
  #   steps:
  #     - *install-git
  #     - *setup-bazel
  #     - *checkout
  #     - *fix-git
  #     - name: Build (ASan)
  #       run: bazel build --config=ci --config=asan //...
  # test-ubsan:
  #   name: test:ubsan
  #   needs: test
  #   runs-on: self-hosted
  #   container: *container-config
  #   steps:
  #     - *install-git
  #     - *setup-bazel
  #     - *checkout
  #     - *fix-git
  #     - name: Build (UBSan)
  #       run: bazel build --config=ci --config=ubsan //...
  # test-tsan:
  #   name: test:tsan
  #   needs: test
  #   runs-on: self-hosted
  #   container: *container-config
  #   steps:
  #     - *install-git
  #     - *setup-bazel
  #     - *checkout
  #     - *fix-git
  #     - name: Build (TSan)
  #       run: bazel build --config=ci --config=tsan //...
  # test-msan:
  #   name: test:msan
  #   needs: test
  #   runs-on: self-hosted
  #   container: *container-config
  #   steps:
  #     - *install-git
  #     - *setup-bazel
  #     - *checkout
  #     - *fix-git
  #     - name: Build (MSan)
  #       run: bazel build --config=ci --config=msan //...
  # test-coverage:
  #   name: test:coverage
  #   needs: test
  #   runs-on: self-hosted
  #   container: *container-config
  #   steps:
  #     - *install-git
  #     - *setup-bazel
  #     - *checkout
  #     - *fix-git
  #     - name: Run tests (coverage)
  #       run: bazel coverage --config=ci //...
  #     - name: Upload coverage report
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: coverage-report
  #         path: bazel-out/_coverage/_coverage_report.dat
